# Generated by Django 2.2.6 on 2020-01-09 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('can_read', models.IntegerField(null=True)),
                ('can_claim', models.IntegerField(null=True)),
                ('can_add', models.IntegerField(null=True)),
                ('can_admin', models.IntegerField(null=True)),
                ('team', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_team', models.CharField(max_length=100)),
                ('access_level', models.IntegerField()),
            ],
            options={
                'unique_together': {('role_team', 'access_level')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('roles', models.ManyToManyField(to='taskmanager.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=1000000000)),
                ('priority', models.IntegerField()),
                ('larger_goal', models.CharField(max_length=10000, null=True)),
                ('estimate_end_date', models.DateField()),
                ('claimants', models.ManyToManyField(related_name='claimed_tasks', to='taskmanager.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='taskmanager.User')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskmanager.List')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000000000000)),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmanager.User')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='taskmanager.Task')),
            ],
        ),
    ]
