# Generated by Django 2.2.6 on 2020-01-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimate_end_date',
            field=models.DateField(null=True),
        ),
    ]
