# Generated by Django 2.2.6 on 2020-01-21 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20200109_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=1000000000000, validators=[django.core.validators.MaxLengthValidator(1000000000000)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1000000000, validators=[django.core.validators.MaxLengthValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='larger_goal',
            field=models.TextField(max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
    ]
