# Generated by Django 2.2.6 on 2019-12-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_auto_20191219_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='taskmanager.Task'),
            preserve_default=False,
        ),
    ]
