# Generated by Django 2.2.6 on 2019-12-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_note_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
